import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'


export default function Home() {
  return (
    <div className={styles.container}>

      <style jsx>
        {`
          h2 {
            font-size: 38px;
          }
          h3 {
            font-size: 28px;
          }
        `}
      </style>
     
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
       
      </Head>
    
      <main className={styles.main}>
        <h1 className={styles.title}>
          <span className='mySpan dummy'>  Hunting Coder</span>
         
        </h1>
        <div className={styles.imagewrap}>
            <Image src='/homeimg.jpg' width={237} height={158} className={styles.myImg}/>
        </div>
        
        <p className={styles.description}>
          A bog for hunting coders by hunting coder
        </p>
        {/* <div className={styles1.con}> */}
        {/* <div className={`${styles1.con} ${styles2.con}`}> */}
        <div >
            <h2>Latest Blog</h2>
            <div className='blogItem'>
              <h3>How to learn Javascript in 2022?</h3>
              <p>Javascript is the language used to design logic for the web</p>
            </div>
            <div className='blogItem'>
              <h3>How to learn Javascript in 2022?</h3>
              <p>Javascript is the language used to design logic for the web</p>
            </div>
            <div className='blogItem'>
              <h3>How to learn Javascript in 2022?</h3>
              <p>Javascript is the language used to design logic for the web</p>
            </div>
        </div>
      </main>

      <footer className={styles.footer}>
       
      </footer>
    </div>
  )
}
