import Head from 'next/head'
import styles from '../styles/Home.module.css'


export default function Home() {
  return (
    <div className={styles.container}>

      <style jsx>
        {`
          h2 {
            font-size: 38px;
          }
          h3 {
            font-size: 28px;
          }
        `}
      </style>
     
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
       
      </Head>
    
        <h1 className={styles.title}>
          <span className='mySpan dummy'>  Hunting Coder</span>
         
        </h1>
        <div className={styles.imagewrap}>
            {/* <Image src='/homeimg.jpg' width={237} height={158} className={styles.myImg}/> */}
            <img src='/homeimg.jpg' width={237} height={158} className={styles.myImg} />
        </div>
        
        <p className={styles.description}>
          A bog for hunting coders by hunting coder
        </p>
        {/* <div className={styles1.con}> */}
        {/* <div className={`${styles1.con} ${styles2.con}`}> */}
        

      <footer className={styles.footer}>
       
      </footer>
    </div>
  )
}
